title: Granta Blue Morris
description: Granta Blue Morris is a Cotswold Morris side based in Cambridge, UK
url: https://www.grantabluemorris.co.uk
facebook:
  publisher: GrantaBlueMorris
logo: officiallogo.png
social:
  links:
    - https://www.instagram.com/grantabluemorris
    - https://www.facebook.com/GrantaBlueMorris
seo:
  type: Organization
lang: en-GB
baseurl: ""
#google_site_verification: 


# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  - dances

sass:
  sass_dir: _scss
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []